version: '3.8'
services:
  mongo:
    image: mongo:6
    restart: unless-stopped
    volumes:
      - mongo-data:/data/db
    ports:
      - "27017:27017"

  redis:
    image: redis:7
    restart: unless-stopped
    ports:
      - "6379:6379"

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    working_dir: /usr/src/app
    volumes:
      - ./backend:/usr/src/app
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/civic_connect
      - REDIS_URL=redis://redis:6379
      - NODE_ENV=development
    depends_on:
      - mongo
      - redis

  worker:
    build:
      context: ./backend
      dockerfile: Dockerfile
    command: npm run worker
    volumes:
      - ./backend:/usr/src/app
    environment:
      - MONGO_URI=mongodb://mongo:27017/civic_connect
      - REDIS_URL=redis://redis:6379
      - NODE_ENV=development
    depends_on:
      - mongo
      - redis

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    depends_on:
      - backend

volumes:
  mongo-data:
