name: Backend CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
      - name: Install backend deps
        run: npm ci
        working-directory: ./backend
      - name: Lint backend
        run: npm run lint
        working-directory: ./backend
      - name: Test backend
        run: npm test
        working-directory: ./backend

  docker-build:
    runs-on: ubuntu-latest
    needs: lint-and-test
    steps:
      - uses: actions/checkout@v4
      - name: Build backend Docker image
        run: docker build -t civic-connect-backend:latest ./backend
